# Generated by Django 4.0.6 on 2022-08-02 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_artwork_artist2_alter_artwork_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='id',
            field=models.CharField(choices=[('LW', 'LW'), ('W', 'W'), ('DW', 'DW'), ('LBl', 'LBl'), ('Bl', 'Bl'), ('DBl', 'DBl'), ('LR', 'LR'), ('R', 'R'), ('DR', 'DR'), ('LY', 'LY'), ('Y', 'Y'), ('DY', 'DY'), ('LBr', 'LBr'), ('Br', 'Br'), ('DBr', 'DBr'), ('LP', 'LP'), ('P', 'P'), ('DP', 'DP'), ('LO', 'LO'), ('O', 'O'), ('DO', 'DO'), ('LG', 'LG'), ('G', 'G'), ('DG', 'DG')], max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='dttg_new_research',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO'), ('unclear', 'UNCLEAR')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='layer2_colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colour_2', to='data.colour'),
        ),
        migrations.AlterField(
            model_name='data',
            name='layer2_composition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='layer3_colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colour_3', to='data.colour'),
        ),
        migrations.AlterField(
            model_name='data',
            name='layer3_composition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='researchers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='sample_link_1',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='sample_link_2',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='sample_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='sample_name_1',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='sample_name_2',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
