# Generated by Django 4.0.6 on 2022-08-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_city_country_alter_city_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
