# Generated by Django 4.0.6 on 2022-08-02 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_museum_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.city'),
        ),
    ]
