# Generated by Django 4.0.6 on 2022-08-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_artist_rkd_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, default='default_artist.jpg', null=True, upload_to='artist_images'),
        ),
    ]
