# Generated by Django 4.0.6 on 2022-08-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='museum_link',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='rkd_link',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
