# Generated by Django 4.0.6 on 2022-08-03 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_artwork_museum_link_alter_artwork_rkd_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='place_of_birth',
            field=models.ForeignKey(on_delete=models.SET('city was deleted'), related_name='birth_place', to='data.city'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='place_of_death',
            field=models.ForeignKey(on_delete=models.SET('city was deleted'), related_name='death_place', to='data.city'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='museum',
            field=models.ForeignKey(on_delete=models.SET('museum was deleted'), to='data.museum'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='place_of_execution',
            field=models.ForeignKey(on_delete=models.SET('city was deleted'), to='data.city'),
        ),
        migrations.AlterField(
            model_name='data',
            name='layer1_colour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colour_1', to='data.colour'),
        ),
        migrations.AlterField(
            model_name='data',
            name='layer1_composition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='layer2_colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colour_2', to='data.colour'),
        ),
        migrations.AlterField(
            model_name='data',
            name='layer3_colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colour_3', to='data.colour'),
        ),
        migrations.AlterField(
            model_name='data',
            name='toplayer_colour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colour_toplayer', to='data.colour'),
        ),
        migrations.AlterField(
            model_name='museum',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('city was deleted'), to='data.city'),
        ),
    ]
