# Generated by Django 4.0.6 on 2022-08-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_artist_place_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colour',
            name='group',
            field=models.CharField(blank=True, default='None', max_length=10, null=True),
        ),
    ]
