# Generated by Django 4.0.6 on 2022-08-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_colour_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='group',
            field=models.CharField(default='default', max_length=10),
            preserve_default=False,
        ),
    ]
