# Generated by Django 4.0.6 on 2022-08-03 10:44

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_colour_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='sample1bf',
            field=models.ImageField(blank=True, default='', upload_to='sample_images'),
        ),
        migrations.AddField(
            model_name='data',
            name='sample1df',
            field=models.ImageField(blank=True, default='', upload_to='sample_images'),
        ),
        migrations.AddField(
            model_name='data',
            name='sample1uv',
            field=models.ImageField(blank=True, default='', upload_to='sample_images'),
        ),
        migrations.AddField(
            model_name='data',
            name='sample2bf',
            field=models.ImageField(blank=True, default='', upload_to='sample_images'),
        ),
        migrations.AddField(
            model_name='data',
            name='sample2df',
            field=models.ImageField(blank=True, default='', upload_to='sample_images'),
        ),
        migrations.AddField(
            model_name='data',
            name='sample2uv',
            field=models.ImageField(blank=True, default='', upload_to='sample_images'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, default='default_artist.jpg', upload_to=data.models.artist_file_name),
        ),
        migrations.AlterField(
            model_name='artist',
            name='rkd_link',
            field=models.URLField(blank=True, default='default'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, default='default_artwork.jpg', upload_to=data.models.artwork_file_name),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='museum_link',
            field=models.URLField(blank=True, default='default'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='rkd_link',
            field=models.URLField(blank=True, default='default'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(blank=True, default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colour',
            name='group',
            field=models.CharField(choices=[('Yellow', 'Yellow'), ('White', 'White'), ('Red', 'Red'), ('Pink', 'Pink'), ('Orange', 'Orange'), ('Grey', 'Grey'), ('Black', 'Black'), ('Brown', 'Brown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='dttg_new_research',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO'), ('unclear', 'UNCLEAR')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='layer1_composition',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='layer2_composition',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='layer3_composition',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='researchers',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='sample_link_1',
            field=models.URLField(blank=True, default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='sample_link_2',
            field=models.URLField(blank=True, default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='sample_location',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='sample_name_1',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='sample_name_2',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='source',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='museum',
            name='website',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
