# Generated by Django 4.0.6 on 2022-08-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_data_sample1bf_data_sample1df_data_sample1uv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='sample_link_1',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='sample_link_2',
            field=models.URLField(blank=True),
        ),
    ]
