# Generated by Django 4.0.6 on 2022-08-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_alter_data_sample_link_1_alter_data_sample_link_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='sample_name_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='sample_name_2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
