# Generated by Django 4.0.6 on 2022-08-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_alter_data_sample_name_1_alter_data_sample_name_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='sample1bf',
        ),
        migrations.RemoveField(
            model_name='data',
            name='sample1df',
        ),
        migrations.RemoveField(
            model_name='data',
            name='sample1uv',
        ),
        migrations.RemoveField(
            model_name='data',
            name='sample2bf',
        ),
        migrations.RemoveField(
            model_name='data',
            name='sample2df',
        ),
        migrations.RemoveField(
            model_name='data',
            name='sample2uv',
        ),
    ]
