# Generated by Django 4.0.6 on 2022-08-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_remove_data_sample1bf_remove_data_sample1df_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='sample1bf',
            field=models.ImageField(blank=True, default='', upload_to='sample_images'),
        ),
        migrations.AddField(
            model_name='data',
            name='sample1df',
            field=models.ImageField(blank=True, default='', upload_to='sample_images'),
        ),
        migrations.AddField(
            model_name='data',
            name='sample1uv',
            field=models.ImageField(blank=True, default='', upload_to='sample_images'),
        ),
        migrations.AddField(
            model_name='data',
            name='sample2bf',
            field=models.ImageField(blank=True, default='', upload_to='sample_images'),
        ),
        migrations.AddField(
            model_name='data',
            name='sample2df',
            field=models.ImageField(blank=True, default='', upload_to='sample_images'),
        ),
        migrations.AddField(
            model_name='data',
            name='sample2uv',
            field=models.ImageField(blank=True, default='', upload_to='sample_images'),
        ),
    ]
