# Generated by Django 4.0.6 on 2022-08-03 10:49

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_data_sample1bf_data_sample1df_data_sample1uv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='sample1bf',
            field=models.ImageField(blank=True, default='', upload_to=data.models.sample1bf_name),
        ),
        migrations.AlterField(
            model_name='data',
            name='sample1df',
            field=models.ImageField(blank=True, default='', upload_to=data.models.sample1df_name),
        ),
        migrations.AlterField(
            model_name='data',
            name='sample1uv',
            field=models.ImageField(blank=True, default='', upload_to=data.models.sample1uv_name),
        ),
        migrations.AlterField(
            model_name='data',
            name='sample2bf',
            field=models.ImageField(blank=True, default='', upload_to=data.models.sample2bf_name),
        ),
        migrations.AlterField(
            model_name='data',
            name='sample2df',
            field=models.ImageField(blank=True, default='', upload_to=data.models.sample2df_name),
        ),
        migrations.AlterField(
            model_name='data',
            name='sample2uv',
            field=models.ImageField(blank=True, default='', upload_to=data.models.sample2uv_name),
        ),
    ]
