# Generated by Django 4.0.6 on 2022-08-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_alter_data_sample1bf_alter_data_sample1df_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='embargo',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
