# Generated by Django 4.0.6 on 2022-08-03 13:37

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_data_embargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(default='artist_images/default_artist.jpg', upload_to=data.models.artist_file_name),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(default='artwork_images/default_artwork.jpg', upload_to=data.models.artwork_file_name),
        ),
    ]
