# Generated by Django 4.0.6 on 2022-08-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_alter_artwork_museum'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='continent',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
