# Generated by Django 4.0.6 on 2022-08-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_city_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='museum_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
