# Generated by Django 4.0.6 on 2022-08-04 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_alter_artwork_place_of_execution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artist_validity',
            field=models.CharField(blank=True, choices=[('copy after', 'Copy after'), ('in the style of', 'In the style of'), ('uncertain', 'Uncertain'), ('attributed to', 'Attributed to'), ('NULL', 'NULL'), ('Workshop of', 'Workshop of')], max_length=30),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='date2',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
