# Generated by Django 4.0.6 on 2022-08-05 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_alter_artwork_artist_validity_alter_artwork_date2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='place_of_birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('city was deleted'), related_name='birth_place', to='data.city'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='place_of_death',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('city was deleted'), related_name='death_place', to='data.city'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='rkd_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='year_of_birth',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2022)]),
        ),
        migrations.AlterField(
            model_name='artist',
            name='year_of_death',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
