# Generated by Django 4.0.6 on 2022-08-05 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_alter_artist_year_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='place_of_birth',
            field=models.ForeignKey(blank=True, default='empty', on_delete=models.SET('city was deleted'), related_name='birth_place', to='data.city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='place_of_death',
            field=models.ForeignKey(blank=True, default='empty', on_delete=models.SET('city was deleted'), related_name='death_place', to='data.city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='rkd_link',
            field=models.URLField(blank=True, default='rmpty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='year_of_birth',
            field=models.IntegerField(blank=True, default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2022)]),
        ),
        migrations.AlterField(
            model_name='artist',
            name='year_of_death',
            field=models.IntegerField(blank=True, default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
