# Generated by Django 4.0.6 on 2022-08-05 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_alter_data_embargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='layer1_colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colour_1', to='data.colour'),
        ),
    ]
