# Generated by Django 4.0.6 on 2022-08-18 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_alter_data_colour_code_alter_data_reliability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='reliability',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
