# Generated by Django 4.1.3 on 2022-12-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_alter_data_reliability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='colour_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='data',
            name='no_of_grounds',
            field=models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('10', 'Ten'), ('>10', 'More than ten')], max_length=3),
        ),
    ]
