# Generated by Django 5.2.13 on 2026-04-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_alter_data_colour_code_alter_data_no_of_grounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='rkd_image_url',
            field=models.URLField(blank=True, help_text='Auto-populated from RKD IIIF API. Run fetch_rkd_images to update.'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='rkd_image_url',
            field=models.URLField(blank=True, help_text='Auto-populated from RKD IIIF API. Run fetch_rkd_images to update.'),
        ),
    ]
